"""Global constants and configuration values"""

# Market constants
MARKET_OPEN_HOUR = 9
MARKET_OPEN_MINUTE = 30
MARKET_CLOSE_HOUR = 15
MARKET_CLOSE_MINUTE = 0

# Risk management
DEFAULT_RISK_PERCENT = 2.0
MAX_POSITION_SIZE = 100
MIN_POSITION_SIZE = 1

# Timing parameters
PREOPEN_WINDOW_MINUTES = 15
INTRADAY_CHECK_INTERVAL_MINUTES = 1
